global proc MayaDmxEnsureExportScripts()
{
    if (!`exists performDmxExport`) {
        source "performDmxExport.mel";
    }

    if (!`exists doDmxExportArgList`) {
        source "doDmxExportArgList.mel";
    }
}

global proc MayaDmxEnsureImportScripts()
{
    if (!`exists performDmxImport`) {
        source "performDmxImport.mel";
    }

    if (!`exists doDmxImportArgList`) {
        source "doDmxImportArgList.mel";
    }
}

global proc MayaDmxShowImportOptions()
{
    MayaDmxEnsureImportScripts();
    performDmxImport 1;
}

global proc MayaDmxShowExportSelectionOptions()
{
    MayaDmxEnsureExportScripts();
    performDmxExport 1 0;
}

global proc MayaDmxShowExportAllOptions()
{
    MayaDmxEnsureExportScripts();
    performDmxExport 1 1;
}
