global proc int mayaDmxTranslatorImport(string $parent,
                                        string $action,
                                        string $initialSettings,
                                        string $resultCallback)
{
    if (!`exists MayaDmxImport_applyOptionsString`) {
        source "performDmxImport.mel";
    }

    if ($action == "post") {
        DmxImportOptionsUI($parent);
        MayaDmxImport_applyOptionsString($initialSettings);
        return 1;
    }

    if ($action == "fill") {
        MayaDmxImport_applyOptionsString($initialSettings);
        return 1;
    }

    if ($action == "query") {
        string $optionsString = MayaDmxImport_collectOptionsString();
        eval($resultCallback + " \"" + $optionsString + "\"");
        return 1;
    }

    return 0;
}
